const lessons=[
 {title:'Lenguajes y paradigmas de programación',text:'Descubre cómo los lenguajes permiten comunicar instrucciones a un computador y cómo los paradigmas organizan la manera de resolver problemas.',questions:[['¿Cuál es un ejemplo de paradigma de programación?',['Programación orientada a objetos','Monitor de 24 pulgadas','Memoria RAM','Teclado mecánico'],0],['¿Qué hace un lenguaje de programación?',['Da instrucciones al computador','Aumenta el brillo','Limpia el teclado','Conecta el mouse'],0],['¿Qué es un algoritmo?',['Pasos ordenados para resolver un problema','Una computadora','Un cable de red','Un monitor'],0],['¿Qué paradigma divide un problema en funciones?',['Funcional','Visual','Manual','Binario'],0],['¿Cuál NO es un lenguaje de programación?',['RAM','Python','JavaScript','C++'],0]]},
 {title:'Introducción a la programación en Python',text:'Python es un lenguaje legible y versátil. Aprenderás variables, tipos de datos y las primeras instrucciones.',questions:[['¿Cómo se muestra un mensaje en Python?',['print("Hola")','show("Hola")','echo("Hola")','write("Hola")'],0],['¿Qué símbolo inicia un comentario en Python?',['#','//','<!--','**'],0],['¿Qué tipo de dato representa un número entero?',['int','str','bool','list'],0],['¿Cuál guarda un texto?',['nombre = "Sasuke"','nombre == "Sasuke"','print = nombre','texto(nombre)'],0],['¿Qué valor booleano es verdadero?',['True','"True"','1.0','yes'],0]]},
 {title:'Operadores algebraicos, relacionales y lógicos',text:'Combina valores, compara condiciones y crea decisiones inteligentes mediante operadores.',questions:[['¿Qué operador comprueba si dos valores son iguales?',['==','=',':=','!='],0],['¿Qué operador representa una suma?',['+','*','/','%'],0],['¿Qué entrega 8 > 3?',['True','False','8','3'],0],['¿Qué operador exige ambas condiciones?',['and','or','not','+'],0],['¿Qué operador significa diferente?',['!=','==','>=','<='],0]]},
 {title:'Estructuras de control condicionales',text:'Usa if, elif y else para que tu programa pueda tomar decisiones.',questions:[['¿Qué estructura se usa para decidir según una condición?',['if','for','print','import'],0],['¿Qué ocurre si if es falsa?',['Puede ejecutarse else','Siempre se repite','El programa se borra','Se crea una variable'],0],['¿Para qué sirve elif?',['Evaluar otra condición','Cerrar Python','Crear un ciclo','Mostrar texto'],0],['¿Qué valor necesita una condición?',['True o False','Una imagen','Un archivo','Un color'],0],['¿Cuál es correcto en Python?',['if edad >= 18:','if edad >= 18','if: edad >= 18','edad if >= 18'],0]]},
 {title:'Estructuras de control repetitivas',text:'Automatiza instrucciones con ciclos for y while para evitar repetir código.',questions:[['¿Qué ciclo se utiliza cuando sabemos cuántas veces repetir?',['for','if','else','def'],0],['¿Qué ciclo continúa mientras se cumpla una condición?',['while','print','input','elif'],0],['¿Qué hace range(3)?',['Genera 0, 1 y 2','Genera 1, 2 y 3','Se repite infinito','Crea una lista vacía'],0],['¿Qué evita un ciclo infinito?',['Actualizar la condición','Quitar los dos puntos','Usar solo print','Cerrar el navegador'],0],['¿Para qué se usan los ciclos?',['Repetir instrucciones','Cambiar colores','Eliminar variables','Crear imágenes'],0]]}
];
const modal=document.querySelector('#lesson-modal'),toast=document.querySelector('#toast'),statusMessage=document.querySelector('#mission-message');let current=0,questionIndex=0,answered=false,correctAnswers=0,completed=new Set([0]);
function showToast(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
function setStatus(message){statusMessage.textContent=message}
function renderQuestion(){const q=lessons[current].questions[questionIndex];answered=false;document.querySelector('#question-count').textContent=`Pregunta ${questionIndex+1} de ${lessons[current].questions.length}`;document.querySelector('#question-progress').style.width=`${((questionIndex+1)/lessons[current].questions.length)*100}%`;document.querySelector('#question').textContent=q[0];document.querySelector('#feedback').textContent='';document.querySelector('#next-question').disabled=true;document.querySelector('#next-question').textContent=questionIndex===lessons[current].questions.length-1?'FINALIZAR DESAFÍO ✓':'SIGUIENTE PREGUNTA →';document.querySelector('#answers').innerHTML=q[1].map((a,i)=>`<button class="answer" data-answer="${i}">${String.fromCharCode(65+i)}. ${a}</button>`).join('');document.querySelectorAll('.answer').forEach(b=>b.addEventListener('click',()=>answer(Number(b.dataset.answer))))}
function renderLesson(index){current=index;questionIndex=0;correctAnswers=0;const lesson=lessons[index];document.querySelector('#modal-title').textContent=lesson.title;document.querySelector('#modal-text').textContent=lesson.text;document.querySelector('#complete').hidden=true;document.querySelector('.mission-actions').hidden=false;renderQuestion();setStatus(`⚡ Misión activa: ${lesson.title}`)}
function answer(choice){if(answered)return;answered=true;const q=lessons[current].questions[questionIndex],right=choice===q[2];if(right)correctAnswers++;document.querySelectorAll('.answer').forEach(b=>{b.disabled=true;const i=Number(b.dataset.answer);if(i===q[2])b.classList.add('correct');else if(i===choice)b.classList.add('incorrect')});document.querySelector('#feedback').textContent=right?'✓ ¡Correcto! Tu Sharingan detectó la respuesta.':'La respuesta correcta está señalada en verde. Aprende y continúa.';document.querySelector('#next-question').disabled=false}
function finishChallenge(){document.querySelector('.mission-actions').hidden=true;const complete=document.querySelector('#complete');complete.hidden=false;complete.textContent=`COMPLETAR MISIÓN · ${correctAnswers}/${lessons[current].questions.length} ACIERTOS +100 XP`;document.querySelector('#feedback').textContent=`Desafío finalizado: ${correctAnswers} de ${lessons[current].questions.length} respuestas correctas.`;document.querySelector('#answers').innerHTML='';document.querySelector('#question').textContent='¡Has terminado todas las preguntas de este nivel!'}
function refresh(){const n=completed.size;document.querySelector('#progress-number').textContent=`${n*20}%`;document.querySelector('#level-count').textContent=`${n} / 5`;document.querySelectorAll('.level').forEach((level,i)=>{const unlocked=i<=n;level.classList.toggle('unlocked',unlocked);level.querySelector('strong').textContent=completed.has(i)?'COMPLETADO':unlocked?'DESBLOQUEAR':'BLOQUEADO';level.querySelector('.mini-progress i').style.width=completed.has(i)?'100%':'0'})}
document.querySelectorAll('.level').forEach((card,index)=>card.addEventListener('click',()=>{if(index>completed.size){showToast('🔒 Completa los niveles anteriores para continuar.');setStatus('🔒 Nivel bloqueado: completa la misión anterior');return}renderLesson(index);modal.showModal()}));document.querySelector('#next-question').addEventListener('click',()=>{if(questionIndex<lessons[current].questions.length-1){questionIndex++;renderQuestion()}else finishChallenge()});function leave(){modal.close();setStatus('✦ Entrenamiento pausado. Puedes volver cuando quieras.')}document.querySelector('.close').addEventListener('click',leave);document.querySelector('#exit-mission').addEventListener('click',leave);document.querySelector('#complete').addEventListener('click',()=>{completed.add(current);refresh();modal.close();setStatus(`✓ Nivel completado: ${lessons[current].title}`);showToast('⚡ Misión completada: +100 XP')});document.querySelector('#sound').addEventListener('click',e=>{e.currentTarget.textContent=e.currentTarget.textContent==='♩'?'♫':'♩';showToast('Modo de sonido actualizado.')});refresh();
