const data=[
 {title:'Algoritmos y sus características',hours:'8 HORAS',img:'nivel-1.png',concept:'Un algoritmo es una secuencia ordenada y finita de pasos que permite resolver un problema.',question:'¿Cuál es una característica de un algoritmo?',options:['Debe ser ambiguo','Debe tener pasos ordenados','No necesita terminar','Solo puede usar números'],answer:1},
 {title:'Diagramas de flujo como herramienta de modelación de algoritmos',hours:'16 HORAS',img:'nivel-2.png',concept:'Los diagramas de flujo representan visualmente los pasos, decisiones y resultados de un algoritmo mediante símbolos.',question:'¿Qué figura se utiliza para representar una decisión?',options:['Rectángulo','Óvalo','Rombo','Flecha'],answer:2},
 {title:'Pseudocódigo: una herramienta de palabras útil',hours:'16 HORAS',img:'nivel-3.png',concept:'El pseudocódigo describe la lógica de una solución con lenguaje claro y palabras clave, sin depender de un lenguaje de programación.',question:'¿Para qué sirve el pseudocódigo?',options:['Diseñar la lógica de un algoritmo','Reemplazar una computadora','Crear imágenes','Guardar archivos'],answer:0},
 {title:'Modelado de problemas',hours:'8 HORAS',img:'nivel-4.png',concept:'Modelar un problema es identificar entradas, procesos y salidas para plantear una solución clara y verificable.',question:'¿Cuál es el primer paso al modelar un problema?',options:['Escribir código','Identificar el problema y sus datos','Comprar un computador','Dibujar cualquier figura'],answer:1}
];
const $=s=>document.querySelector(s),modal=$('#modal'),state=JSON.parse(localStorage.getItem('naruto-unidad2')||'{"done":[0],"points":120}');state.done=[...new Set(state.done||[0])];
function save(){localStorage.setItem('naruto-unidad2',JSON.stringify(state))}function unlock(i){return i===0||state.done.includes(i-1)}
function render(){const box=$('#levels');box.innerHTML=data.map((item,i)=>{const done=state.done.includes(i),open=unlock(i);return `<button class="level-card ${done?'done':''} ${!open?'locked':''}" data-level="${i}"><img src="img/imagen_unidad2/recortes/${item.img}" alt=""><span class="badge">${done?'✓':i+1}</span><b>${item.title}</b><small>◷ ${item.hours}</small><em>${done?'COMPLETADO':open?'ENTRENAR':'🔒 BLOQUEADO'}</em><i>${done?'100':'0'}%</i></button>`}).join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>openLevel(+b.dataset.level));const done=state.done.length,percent=Math.round(done/4*100);$('#completed').textContent=`${done} / 4`;$('#lessons').textContent=`${done*4} / 16`;$('#exercises').textContent=`${done*8} / 32`;$('#points').textContent=state.points;$('#totalxp').textContent=`${state.points} XP`;$('#percentage').textContent=`${percent}%`;document.documentElement.style.setProperty('--progress',`${percent*3.6}deg`);$('#exam').classList.toggle('open',done===4);$('#exam small').textContent=done===4?'¡DESBLOQUEADO!':'🔒 BLOQUEADO'}
function openLevel(i){if(!unlock(i)){notice('NIVEL BLOQUEADO','Completa el nivel anterior para abrir este entrenamiento.');return}const t=data[i];$('#modal-content').innerHTML=`<p class="eyebrow">NIVEL ${i+1} · ${t.hours}</p><h2>${t.title}</h2><p class="concept">${t.concept}</p><h3>RETO NINJA</h3><p>${t.question}</p><div class="answers">${t.options.map((x,n)=>`<button data-answer="${n}">${'ABCD'[n]} · ${x}</button>`).join('')}</div><p id="result"></p>`;modal.showModal();document.querySelectorAll('.answers button').forEach(b=>b.onclick=()=>{const ok=+b.dataset.answer===t.answer;document.querySelectorAll('.answers button').forEach((x,n)=>{x.disabled=true;x.classList.toggle('correct',n===t.answer)});$('#result').textContent=ok?'✓ ¡Correcto! Nivel completado y siguiente nivel desbloqueado.':'La respuesta correcta está marcada en verde.';if(ok&&!state.done.includes(i)){state.done.push(i);state.points+=50;save();render()}})}
function notice(title,text){$('#modal-content').innerHTML=`<h2>${title}</h2><p class="concept">${text}</p>`;modal.showModal()}$('#exam').onclick=()=>state.done.length===4?notice('EXAMEN FINAL','¡Misión cumplida! Has desbloqueado el examen final de la Unidad 2.'):notice('EXAMEN BLOQUEADO',`Completa ${4-state.done.length} nivel(es) para desbloquearlo.`);document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>notice(b.dataset.panel.toUpperCase(),'Este panel se activará con tu progreso de ninja.'));document.querySelectorAll('[data-reward]').forEach(b=>b.onclick=()=>notice('RECOMPENSA',state.done.length===4?`¡Has desbloqueado: ${b.dataset.reward}!`:'Completa los cuatro niveles para reclamar esta recompensa.'));modal.querySelector('.close').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});render();
