const lessons=[
 {title:'Lenguajes y paradigmas de programación',text:'Descubre cómo los lenguajes permiten comunicar instrucciones a un computador y cómo los paradigmas organizan la manera de resolver problemas.',q:'¿Cuál es un ejemplo de paradigma de programación?',a:['Programación orientada a objetos','Monitor de 24 pulgadas','Memoria RAM','Teclado mecánico'],ok:0},
 {title:'Introducción a la programación en Python',text:'Python es un lenguaje legible y versátil. Aprenderás variables, tipos de datos y las primeras instrucciones.',q:'¿Cómo se muestra un mensaje en Python?',a:['print("Hola")','show("Hola")','echo("Hola")','write("Hola")'],ok:0},
 {title:'Operadores algebraicos, relacionales y lógicos',text:'Combina valores, compara condiciones y crea decisiones inteligentes mediante operadores.',q:'¿Qué operador comprueba si dos valores son iguales?',a:['==','=',':=','!='],ok:0},
 {title:'Estructuras de control condicionales',text:'Usa if, elif y else para que tu programa pueda tomar decisiones.',q:'¿Qué estructura se usa para decidir según una condición?',a:['if','for','print','import'],ok:0},
 {title:'Estructuras de control repetitivas',text:'Automatiza instrucciones con ciclos for y while para evitar repetir código.',q:'¿Qué ciclo se utiliza cuando sabemos cuántas veces repetir?',a:['for','if','else','def'],ok:0}
];
const modal=document.querySelector('#lesson-modal'),toast=document.querySelector('#toast');let current=0,answered=false,completed=new Set([0]);
function showToast(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
function renderLesson(index){current=index;answered=false;const lesson=lessons[index];document.querySelector('#modal-title').textContent=lesson.title;document.querySelector('#modal-text').textContent=lesson.text;document.querySelector('#question').textContent=lesson.q;document.querySelector('#feedback').textContent='';document.querySelector('#answers').innerHTML=lesson.a.map((answer,i)=>`<button class="answer" data-answer="${i}">${String.fromCharCode(65+i)}. ${answer}</button>`).join('');document.querySelectorAll('.answer').forEach(button=>button.addEventListener('click',()=>answer(Number(button.dataset.answer))));document.querySelector('#complete').textContent=completed.has(index)?'MISIÓN YA COMPLETADA ✓':'COMPLETAR MISIÓN +100 XP'}
function answer(choice){if(answered)return;answered=true;const lesson=lessons[current],right=choice===lesson.ok;document.querySelectorAll('.answer').forEach(button=>{button.disabled=true;const i=Number(button.dataset.answer);if(i===lesson.ok)button.classList.add('correct');else if(i===choice)button.classList.add('incorrect')});document.querySelector('#feedback').textContent=right?'✓ Excelente. Has dominado este jutsu de lógica.':'La respuesta correcta está señalada en verde. ¡Sigue entrenando!'}
function refresh(){const n=completed.size;document.querySelector('#progress-number').textContent=`${n*20}%`;document.querySelector('#level-count').textContent=`${n} / 5`;document.querySelectorAll('.level').forEach((level,i)=>{const unlocked=i<=n;level.classList.toggle('unlocked',unlocked);level.querySelector('strong').textContent=completed.has(i)?'COMPLETADO':unlocked?'DESBLOQUEAR':'BLOQUEADO';level.querySelector('.mini-progress i').style.width=completed.has(i)?'100%':'0'});}
document.querySelectorAll('.level').forEach((card,index)=>card.addEventListener('click',()=>{if(index>completed.size){showToast('🔒 Completa los niveles anteriores para continuar.');return}renderLesson(index);modal.showModal()}));
document.querySelector('.close').addEventListener('click',()=>modal.close());document.querySelector('#complete').addEventListener('click',()=>{if(!answered){showToast('Resuelve primero el desafío rápido.');return}completed.add(current);refresh();renderLesson(current);showToast('⚡ Misión completada: +100 XP');});document.querySelector('#sound').addEventListener('click',e=>{e.currentTarget.textContent=e.currentTarget.textContent==='♩'?'♫':'♩';showToast('Modo de sonido actualizado.');});refresh();
